### ISSUE TITLE
1.2 kHz tone fill sent at the beginning of every DMR DMO transmission

### ISSUE THREAD

**Issue by heidi-ho** [juribeparada/MMDVM_HS#44]
Commit ecc597b "Replacing 1.2 kHz tone fill by pseudo random fill (DMR DMO)" didn't eliminate the 1.2 kHz tone on the output of my Zumspot board attached to a RPi Zero W. See DMRDMOTX.cpp lines 73-91.

    if (m_poLen > 0U) {
      uint16_t space = io.getSpace();

        while (space > 8U) {
          if (m_delay) {
            m_poPtr++;
            writeByte(DMR_SYNC);
          } else
            writeByte(m_poBuffer[m_poPtr++]);   

          space -= 8U;
      
          if (m_poPtr >= m_poLen) {
            m_poPtr = 0U;
            m_poLen = 0U;
            m_delay = false;
            return;
          }
     }
 
On my system, the 1.2 kHz tone is generated by the code "writeByte(DMR_SYNC)" shown above.

Though this issue isn't critical for me (as my DMR radios ignore the spurious tone) and is mainly an annoyance, the behavior certainly does not conform to the DMR specification.

**Comment by juribeparada** [comment]
The commit ecc597b "Replacing 1.2 kHz tone fill by pseudo random fill (DMR DMO)" has nothing to do with the beginning SYNC tone, it was to replace the original MMDVM fill between slots (the "empty slot" in DMO). I've just left the initial SYNC sequence because from the MMDVM experience, this sync helped the decoding in some old DMR radios.
